In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import ipaddress
import socket 
import struct

In [2]:
fraud=pd.read_csv(r"C:\Users\pc\Fraud-Detection\data\fraud_cleaned.csv")
credit=pd.read_csv(r"C:\Users\pc\Fraud-Detection\data\credit_clean.csv")
ip=pd.read_csv(r'C:\Users\pc\Fraud-Detection\data\ip_clean.csv')

In [3]:
print(fraud['ip_address'].dtype)

float64

In [4]:
def int_to_ip(x):
    try:
        return socket.inet_ntoa(struct.pack("!I", int(float(x))))
    except:
        return None

fraud['ip_address_str'] = fraud['ip_address'].apply(int_to_ip)

In [5]:
fraud = fraud[fraud['ip_address_str'].str.count(r'\.') == 3]

In [6]:
fraud['purchase_time']=pd.to_datetime(fraud['purchase_time'])
#fraud['purchase_time']=pd.to_datetime(fraud['purchase_time'])

fraud['hour_of_day']=fraud['purchase_time'].dt.hour

In [7]:
fraud['week_day']=fraud['purchase_time'].dt.weekday

In [8]:
fraud.drop(columns='ip_address',inplace=True)

In [9]:
fraud.rename(columns={'ip_address_str':'ip_address'}, inplace=True)

In [10]:
fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,class,ip_address,hour_of_day,week_day
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,34,QVPSPJUOCKZAR,SEO,Chrome,M,39,0,43.173.1.96,2,5
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,16,EOGFQPIZPYXFZ,Ads,Chrome,F,53,0,20.225.83.219,1,0
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,15,YSSKYOSJHPPLJ,SEO,Opera,M,53,1,156.64.132.28,18,3
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,44,ATGTXKYKUDUQN,SEO,Safari,M,41,0,228.234.6.235,13,0
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,39,NAUITBZFJKHWW,Ads,Safari,M,45,0,24.197.75.141,18,2

In [11]:
fraud.to_csv(r"C:\Users\pc\Fraud-Detection\data\fraudd.csv", index=False)

In [12]:
fraud=pd.read_csv(r'C:\Users\pc\Fraud-Detection\data\fraudd.csv')

In [13]:
fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,class,ip_address,hour_of_day,week_day
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,34,QVPSPJUOCKZAR,SEO,Chrome,M,39,0,43.173.1.96,2,5
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,16,EOGFQPIZPYXFZ,Ads,Chrome,F,53,0,20.225.83.219,1,0
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,15,YSSKYOSJHPPLJ,SEO,Opera,M,53,1,156.64.132.28,18,3
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,44,ATGTXKYKUDUQN,SEO,Safari,M,41,0,228.234.6.235,13,0
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,39,NAUITBZFJKHWW,Ads,Safari,M,45,0,24.197.75.141,18,2

In [14]:


fraud['ip_int'] = fraud['ip_address'].apply(lambda x: int(ipaddress.IPv4Address(x)))

In [15]:
ip['lower_bound_ip_address'] = ip['lower_bound_ip_address'].astype(float).astype(int)
ip['upper_bound_ip_address'] = ip['upper_bound_ip_address'].astype(float).astype(int)

In [16]:
ip['lower_bound_ip_address'] = ip['lower_bound_ip_address'].apply(ipaddress.IPv4Address).astype(int)
ip['upper_bound_ip_address'] = ip['upper_bound_ip_address'].apply(ipaddress.IPv4Address).astype(int)

In [17]:
ip.head()

   lower_bound_ip_address  upper_bound_ip_address    country
0                16777216                16777471  Australia
1                16777472                16777727      China
2                16777728                16778239      China
3                16778240                16779263  Australia
4                16779264                16781311      China

In [18]:
fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,class,ip_address,hour_of_day,week_day,ip_int
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,34,QVPSPJUOCKZAR,SEO,Chrome,M,39,0,43.173.1.96,2,5,732758368
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,16,EOGFQPIZPYXFZ,Ads,Chrome,F,53,0,20.225.83.219,1,0,350311387
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,15,YSSKYOSJHPPLJ,SEO,Opera,M,53,1,156.64.132.28,18,3,2621473820
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,44,ATGTXKYKUDUQN,SEO,Safari,M,41,0,228.234.6.235,13,0,3840542443
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,39,NAUITBZFJKHWW,Ads,Safari,M,45,0,24.197.75.141,18,2,415583117

In [20]:
def map_country(ip_val):
    row = ip[(ip['lower_bound_ip_address'] <= ip_val) & (ip['upper_bound_ip_address'] >= ip_val)]
    return row['country'].values[0] if not row.empty else 'Unknown'

fraud['country'] = fraud['ip_int'].apply(map_country)

In [21]:
fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,class,ip_address,hour_of_day,week_day,ip_int,country
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,34,QVPSPJUOCKZAR,SEO,Chrome,M,39,0,43.173.1.96,2,5,732758368,Japan
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,16,EOGFQPIZPYXFZ,Ads,Chrome,F,53,0,20.225.83.219,1,0,350311387,United States
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,15,YSSKYOSJHPPLJ,SEO,Opera,M,53,1,156.64.132.28,18,3,2621473820,United States
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,44,ATGTXKYKUDUQN,SEO,Safari,M,41,0,228.234.6.235,13,0,3840542443,Unknown
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,39,NAUITBZFJKHWW,Ads,Safari,M,45,0,24.197.75.141,18,2,415583117,United States

In [28]:
fraud['signup_time'] = pd.to_datetime(fraud['signup_time'])
fraud['purchase_time']=pd.to_datetime(fraud['purchase_time'])

In [29]:
fraud['time_since_signup'] = (fraud['purchase_time'] - fraud['signup_time']).dt.total_seconds() / 3600

In [30]:
fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,class,ip_address,hour_of_day,week_day,ip_int,country,time_since_signup
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,34,QVPSPJUOCKZAR,SEO,Chrome,M,39,0,43.173.1.96,2,5,732758368,Japan,1251.856111
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,16,EOGFQPIZPYXFZ,Ads,Chrome,F,53,0,20.225.83.219,1,0,350311387,United States,4.984444
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,15,YSSKYOSJHPPLJ,SEO,Opera,M,53,1,156.64.132.28,18,3,2621473820,United States,0.000278
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,44,ATGTXKYKUDUQN,SEO,Safari,M,41,0,228.234.6.235,13,0,3840542443,Unknown,136.690278
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,39,NAUITBZFJKHWW,Ads,Safari,M,45,0,24.197.75.141,18,2,415583117,United States,1211.516944

In [32]:
# Check how many invalid rows
negative_count = fraud[fraud['time_since_signup'] < 0].shape[0]
print(f"Found {negative_count} rows with negative time_since_signup")

Found 0 rows with negative time_since_signup

In [34]:
fraud.to_csv('C:/Users/pc/Fraud-Detection/data/fraud.csv', index=False)